parameters:
    igorw.file_serve.response.factory.class: Igorw\FileServeBundle\Response\PhpResponseFactory

services:
    igorw.file_serve.response.factory:
        class: %igorw.file_serve.response.factory.class%
